language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer update

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHP_UNIT_FLAGS="--coverage-clover=coverage.clover"; fi

script:
  - phpunit $PHP_UNIT_FLAGS

after_script:
  # move code coverage
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
